//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.10 at 02:45:28 PM PST 
//


package com.relteq.sirius.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}display_position" minOccurs="0"/>
 *         &lt;element ref="{}targetElements"/>
 *         &lt;element ref="{}feedbackElements" minOccurs="0"/>
 *         &lt;element ref="{}parameters" minOccurs="0"/>
 *         &lt;element ref="{}qcontroller" minOccurs="0"/>
 *         &lt;element ref="{}table" minOccurs="0"/>
 *         &lt;element ref="{}PlanSequence" minOccurs="0"/>
 *         &lt;element ref="{}PlanList" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="link_position" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="IRM alinea|IRM time of day|IRM traffic responsive|CRM swarm|CRM hero|VSL time of day|SIG pretimed|SIG actuated"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="dt" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "controller")
public class Controller {

    @XmlElement(name = "display_position")
    protected DisplayPosition displayPosition;
    @XmlElement(required = true)
    protected TargetElements targetElements;
    protected FeedbackElements feedbackElements;
    protected Parameters parameters;
    protected Qcontroller qcontroller;
    protected Table table;
    @XmlElement(name = "PlanSequence")
    protected PlanSequence planSequence;
    @XmlElement(name = "PlanList")
    protected PlanList planList;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "link_position")
    protected BigDecimal linkPosition;
    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "dt", required = true)
    protected BigDecimal dt;

    /**
     * Gets the value of the displayPosition property.
     * 
     * @return
     *     possible object is
     *     {@link DisplayPosition }
     *     
     */
    public DisplayPosition getDisplayPosition() {
        return displayPosition;
    }

    /**
     * Sets the value of the displayPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisplayPosition }
     *     
     */
    public void setDisplayPosition(DisplayPosition value) {
        this.displayPosition = value;
    }

    /**
     * Gets the value of the targetElements property.
     * 
     * @return
     *     possible object is
     *     {@link TargetElements }
     *     
     */
    public TargetElements getTargetElements() {
        return targetElements;
    }

    /**
     * Sets the value of the targetElements property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetElements }
     *     
     */
    public void setTargetElements(TargetElements value) {
        this.targetElements = value;
    }

    /**
     * Gets the value of the feedbackElements property.
     * 
     * @return
     *     possible object is
     *     {@link FeedbackElements }
     *     
     */
    public FeedbackElements getFeedbackElements() {
        return feedbackElements;
    }

    /**
     * Sets the value of the feedbackElements property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeedbackElements }
     *     
     */
    public void setFeedbackElements(FeedbackElements value) {
        this.feedbackElements = value;
    }

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link Parameters }
     *     
     */
    public Parameters getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parameters }
     *     
     */
    public void setParameters(Parameters value) {
        this.parameters = value;
    }

    /**
     * Gets the value of the qcontroller property.
     * 
     * @return
     *     possible object is
     *     {@link Qcontroller }
     *     
     */
    public Qcontroller getQcontroller() {
        return qcontroller;
    }

    /**
     * Sets the value of the qcontroller property.
     * 
     * @param value
     *     allowed object is
     *     {@link Qcontroller }
     *     
     */
    public void setQcontroller(Qcontroller value) {
        this.qcontroller = value;
    }

    /**
     * Gets the value of the table property.
     * 
     * @return
     *     possible object is
     *     {@link Table }
     *     
     */
    public Table getTable() {
        return table;
    }

    /**
     * Sets the value of the table property.
     * 
     * @param value
     *     allowed object is
     *     {@link Table }
     *     
     */
    public void setTable(Table value) {
        this.table = value;
    }

    /**
     * Gets the value of the planSequence property.
     * 
     * @return
     *     possible object is
     *     {@link PlanSequence }
     *     
     */
    public PlanSequence getPlanSequence() {
        return planSequence;
    }

    /**
     * Sets the value of the planSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanSequence }
     *     
     */
    public void setPlanSequence(PlanSequence value) {
        this.planSequence = value;
    }

    /**
     * Gets the value of the planList property.
     * 
     * @return
     *     possible object is
     *     {@link PlanList }
     *     
     */
    public PlanList getPlanList() {
        return planList;
    }

    /**
     * Sets the value of the planList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanList }
     *     
     */
    public void setPlanList(PlanList value) {
        this.planList = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the linkPosition property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLinkPosition() {
        return linkPosition;
    }

    /**
     * Sets the value of the linkPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLinkPosition(BigDecimal value) {
        this.linkPosition = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the dt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDt() {
        return dt;
    }

    /**
     * Sets the value of the dt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDt(BigDecimal value) {
        this.dt = value;
    }

}
