//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.29 at 04:19:00 PM PST 
//


package com.relteq.sirius.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="path_segment_in" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="path_segment_out" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "decision_point_split")
public class DecisionPointSplit {

    @XmlAttribute(name = "path_segment_in", required = true)
    protected String pathSegmentIn;
    @XmlAttribute(name = "path_segment_out", required = true)
    protected String pathSegmentOut;

    /**
     * Gets the value of the pathSegmentIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPathSegmentIn() {
        return pathSegmentIn;
    }

    /**
     * Sets the value of the pathSegmentIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPathSegmentIn(String value) {
        this.pathSegmentIn = value;
    }

    /**
     * Gets the value of the pathSegmentOut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPathSegmentOut() {
        return pathSegmentOut;
    }

    /**
     * Sets the value of the pathSegmentOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPathSegmentOut(String value) {
        this.pathSegmentOut = value;
    }

}
