//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.30 at 08:17:18 PM PST 
//


package com.relteq.sirius.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}description" minOccurs="0"/>
 *         &lt;element ref="{}display_position" minOccurs="0"/>
 *         &lt;element ref="{}targetElements"/>
 *         &lt;element ref="{}fundamentalDiagram" minOccurs="0"/>
 *         &lt;element ref="{}lane_count_change" minOccurs="0"/>
 *         &lt;element ref="{}on_off_switch" minOccurs="0"/>
 *         &lt;element ref="{}knob" minOccurs="0"/>
 *         &lt;element ref="{}splitratioProfile" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="reset_to_nominal" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="tstamp" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="enabled" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="fundamental diagram|link demand knob|link lanes|node split ratio|control toggle|global control toggle|global demand knob"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "event")
public class Event {

    protected String description;
    @XmlElement(name = "display_position")
    protected DisplayPosition displayPosition;
    @XmlElement(required = true)
    protected TargetElements targetElements;
    protected FundamentalDiagram fundamentalDiagram;
    @XmlElement(name = "lane_count_change")
    protected LaneCountChange laneCountChange;
    @XmlElement(name = "on_off_switch")
    protected OnOffSwitch onOffSwitch;
    protected Knob knob;
    protected SplitratioProfile splitratioProfile;
    @XmlAttribute(name = "reset_to_nominal")
    protected Boolean resetToNominal;
    @XmlAttribute(name = "tstamp", required = true)
    protected BigDecimal tstamp;
    @XmlAttribute(name = "enabled", required = true)
    protected boolean enabled;
    @XmlAttribute(name = "type", required = true)
    protected String type;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the displayPosition property.
     * 
     * @return
     *     possible object is
     *     {@link DisplayPosition }
     *     
     */
    public DisplayPosition getDisplayPosition() {
        return displayPosition;
    }

    /**
     * Sets the value of the displayPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisplayPosition }
     *     
     */
    public void setDisplayPosition(DisplayPosition value) {
        this.displayPosition = value;
    }

    /**
     * Gets the value of the targetElements property.
     * 
     * @return
     *     possible object is
     *     {@link TargetElements }
     *     
     */
    public TargetElements getTargetElements() {
        return targetElements;
    }

    /**
     * Sets the value of the targetElements property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetElements }
     *     
     */
    public void setTargetElements(TargetElements value) {
        this.targetElements = value;
    }

    /**
     * Gets the value of the fundamentalDiagram property.
     * 
     * @return
     *     possible object is
     *     {@link FundamentalDiagram }
     *     
     */
    public FundamentalDiagram getFundamentalDiagram() {
        return fundamentalDiagram;
    }

    /**
     * Sets the value of the fundamentalDiagram property.
     * 
     * @param value
     *     allowed object is
     *     {@link FundamentalDiagram }
     *     
     */
    public void setFundamentalDiagram(FundamentalDiagram value) {
        this.fundamentalDiagram = value;
    }

    /**
     * Gets the value of the laneCountChange property.
     * 
     * @return
     *     possible object is
     *     {@link LaneCountChange }
     *     
     */
    public LaneCountChange getLaneCountChange() {
        return laneCountChange;
    }

    /**
     * Sets the value of the laneCountChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link LaneCountChange }
     *     
     */
    public void setLaneCountChange(LaneCountChange value) {
        this.laneCountChange = value;
    }

    /**
     * Gets the value of the onOffSwitch property.
     * 
     * @return
     *     possible object is
     *     {@link OnOffSwitch }
     *     
     */
    public OnOffSwitch getOnOffSwitch() {
        return onOffSwitch;
    }

    /**
     * Sets the value of the onOffSwitch property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnOffSwitch }
     *     
     */
    public void setOnOffSwitch(OnOffSwitch value) {
        this.onOffSwitch = value;
    }

    /**
     * Gets the value of the knob property.
     * 
     * @return
     *     possible object is
     *     {@link Knob }
     *     
     */
    public Knob getKnob() {
        return knob;
    }

    /**
     * Sets the value of the knob property.
     * 
     * @param value
     *     allowed object is
     *     {@link Knob }
     *     
     */
    public void setKnob(Knob value) {
        this.knob = value;
    }

    /**
     * Gets the value of the splitratioProfile property.
     * 
     * @return
     *     possible object is
     *     {@link SplitratioProfile }
     *     
     */
    public SplitratioProfile getSplitratioProfile() {
        return splitratioProfile;
    }

    /**
     * Sets the value of the splitratioProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link SplitratioProfile }
     *     
     */
    public void setSplitratioProfile(SplitratioProfile value) {
        this.splitratioProfile = value;
    }

    /**
     * Gets the value of the resetToNominal property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isResetToNominal() {
        if (resetToNominal == null) {
            return false;
        } else {
            return resetToNominal;
        }
    }

    /**
     * Sets the value of the resetToNominal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setResetToNominal(Boolean value) {
        this.resetToNominal = value;
    }

    /**
     * Gets the value of the tstamp property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTstamp() {
        return tstamp;
    }

    /**
     * Sets the value of the tstamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTstamp(BigDecimal value) {
        this.tstamp = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     */
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     */
    public void setEnabled(boolean value) {
        this.enabled = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
