//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.10 at 02:45:28 PM PST 
//


package com.relteq.sirius.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="densityCritical" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="capacity" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="densityJam" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="capacityDrop" type="{http://www.w3.org/2001/XMLSchema}string" default="0.0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "fundamentalDiagram")
public class FundamentalDiagram {

    @XmlAttribute(name = "densityCritical")
    protected String densityCritical;
    @XmlAttribute(name = "capacity")
    protected String capacity;
    @XmlAttribute(name = "densityJam")
    protected String densityJam;
    @XmlAttribute(name = "capacityDrop")
    protected String capacityDrop;

    /**
     * Gets the value of the densityCritical property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDensityCritical() {
        return densityCritical;
    }

    /**
     * Sets the value of the densityCritical property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDensityCritical(String value) {
        this.densityCritical = value;
    }

    /**
     * Gets the value of the capacity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapacity() {
        return capacity;
    }

    /**
     * Sets the value of the capacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapacity(String value) {
        this.capacity = value;
    }

    /**
     * Gets the value of the densityJam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDensityJam() {
        return densityJam;
    }

    /**
     * Sets the value of the densityJam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDensityJam(String value) {
        this.densityJam = value;
    }

    /**
     * Gets the value of the capacityDrop property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapacityDrop() {
        if (capacityDrop == null) {
            return "0.0";
        } else {
            return capacityDrop;
        }
    }

    /**
     * Sets the value of the capacityDrop property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapacityDrop(String value) {
        this.capacityDrop = value;
    }

}
