//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.14 at 11:41:53 AM PST 
//


package com.relteq.sirius.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="freeflow_speed" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="congestion_speed" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="capacity" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="densityJam" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="capacityDrop" type="{http://www.w3.org/2001/XMLSchema}decimal" default="0.0" />
 *       &lt;attribute name="std_dev_capacity" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "fundamentalDiagram")
public class FundamentalDiagram {

    @XmlAttribute(name = "freeflow_speed")
    protected BigDecimal freeflowSpeed;
    @XmlAttribute(name = "congestion_speed")
    protected BigDecimal congestionSpeed;
    @XmlAttribute(name = "capacity")
    protected BigDecimal capacity;
    @XmlAttribute(name = "densityJam")
    protected BigDecimal densityJam;
    @XmlAttribute(name = "capacityDrop")
    protected BigDecimal capacityDrop;
    @XmlAttribute(name = "std_dev_capacity")
    protected BigDecimal stdDevCapacity;

    /**
     * Gets the value of the freeflowSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFreeflowSpeed() {
        return freeflowSpeed;
    }

    /**
     * Sets the value of the freeflowSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFreeflowSpeed(BigDecimal value) {
        this.freeflowSpeed = value;
    }

    /**
     * Gets the value of the congestionSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCongestionSpeed() {
        return congestionSpeed;
    }

    /**
     * Sets the value of the congestionSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCongestionSpeed(BigDecimal value) {
        this.congestionSpeed = value;
    }

    /**
     * Gets the value of the capacity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCapacity() {
        return capacity;
    }

    /**
     * Sets the value of the capacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCapacity(BigDecimal value) {
        this.capacity = value;
    }

    /**
     * Gets the value of the densityJam property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDensityJam() {
        return densityJam;
    }

    /**
     * Sets the value of the densityJam property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDensityJam(BigDecimal value) {
        this.densityJam = value;
    }

    /**
     * Gets the value of the capacityDrop property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCapacityDrop() {
        if (capacityDrop == null) {
            return new BigDecimal("0.0");
        } else {
            return capacityDrop;
        }
    }

    /**
     * Sets the value of the capacityDrop property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCapacityDrop(BigDecimal value) {
        this.capacityDrop = value;
    }

    /**
     * Gets the value of the stdDevCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getStdDevCapacity() {
        return stdDevCapacity;
    }

    /**
     * Sets the value of the stdDevCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setStdDevCapacity(BigDecimal value) {
        this.stdDevCapacity = value;
    }

}
