//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.30 at 08:17:18 PM PST 
//


package com.relteq.sirius.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}linkpair" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="network_a" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="network_b" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "linkpair"
})
@XmlRootElement(name = "nertworkpair")
public class Nertworkpair {

    protected List<Linkpair> linkpair;
    @XmlAttribute(name = "network_a", required = true)
    protected String networkA;
    @XmlAttribute(name = "network_b", required = true)
    protected String networkB;

    /**
     * Gets the value of the linkpair property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the linkpair property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinkpair().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Linkpair }
     * 
     * 
     */
    public List<Linkpair> getLinkpair() {
        if (linkpair == null) {
            linkpair = new ArrayList<Linkpair>();
        }
        return this.linkpair;
    }

    /**
     * Gets the value of the networkA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkA() {
        return networkA;
    }

    /**
     * Sets the value of the networkA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkA(String value) {
        this.networkA = value;
    }

    /**
     * Gets the value of the networkB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkB() {
        return networkB;
    }

    /**
     * Sets the value of the networkB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkB(String value) {
        this.networkB = value;
    }

}
