//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.21 at 10:10:31 PM PST 
//


package com.relteq.sirius.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.relteq.sirius.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Levels_QNAME = new QName("", "Levels");
    private final static QName _PathSegments_QNAME = new QName("", "path_segments");
    private final static QName _Postmile_QNAME = new QName("", "postmile");
    private final static QName _Description_QNAME = new QName("", "description");
    private final static QName _DecisionPoints_QNAME = new QName("", "decision_points");
    private final static QName _Points_QNAME = new QName("", "Points");
    private final static QName _Units_QNAME = new QName("", "units");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.relteq.sirius.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FundamentalDiagram }
     * 
     */
    public FundamentalDiagram createFundamentalDiagram() {
        return new FundamentalDiagram();
    }

    /**
     * Create an instance of {@link SplitratioProfile }
     * 
     */
    public SplitratioProfile createSplitratioProfile() {
        return new SplitratioProfile();
    }

    /**
     * Create an instance of {@link Splitratio }
     * 
     */
    public Splitratio createSplitratio() {
        return new Splitratio();
    }

    /**
     * Create an instance of {@link DisplayPosition }
     * 
     */
    public DisplayPosition createDisplayPosition() {
        return new DisplayPosition();
    }

    /**
     * Create an instance of {@link Point }
     * 
     */
    public Point createPoint() {
        return new Point();
    }

    /**
     * Create an instance of {@link DecisionPoints }
     * 
     */
    public DecisionPoints createDecisionPoints() {
        return new DecisionPoints();
    }

    /**
     * Create an instance of {@link DecisionPoint }
     * 
     */
    public DecisionPoint createDecisionPoint() {
        return new DecisionPoint();
    }

    /**
     * Create an instance of {@link VehicleTypeOrder }
     * 
     */
    public VehicleTypeOrder createVehicleTypeOrder() {
        return new VehicleTypeOrder();
    }

    /**
     * Create an instance of {@link VehicleType }
     * 
     */
    public VehicleType createVehicleType() {
        return new VehicleType();
    }

    /**
     * Create an instance of {@link DecisionPointSplit }
     * 
     */
    public DecisionPointSplit createDecisionPointSplit() {
        return new DecisionPointSplit();
    }

    /**
     * Create an instance of {@link Settings }
     * 
     */
    public Settings createSettings() {
        return new Settings();
    }

    /**
     * Create an instance of {@link VehicleTypes }
     * 
     */
    public VehicleTypes createVehicleTypes() {
        return new VehicleTypes();
    }

    /**
     * Create an instance of {@link DataSource }
     * 
     */
    public DataSource createDataSource() {
        return new DataSource();
    }

    /**
     * Create an instance of {@link EncodedPolyline }
     * 
     */
    public EncodedPolyline createEncodedPolyline() {
        return new EncodedPolyline();
    }

    /**
     * Create an instance of {@link OdDemandProfile }
     * 
     */
    public OdDemandProfile createOdDemandProfile() {
        return new OdDemandProfile();
    }

    /**
     * Create an instance of {@link LaneCountChange }
     * 
     */
    public LaneCountChange createLaneCountChange() {
        return new LaneCountChange();
    }

    /**
     * Create an instance of {@link InitialDensityProfile }
     * 
     */
    public InitialDensityProfile createInitialDensityProfile() {
        return new InitialDensityProfile();
    }

    /**
     * Create an instance of {@link Density }
     * 
     */
    public Density createDensity() {
        return new Density();
    }

    /**
     * Create an instance of {@link DirectionsCacheEntry }
     * 
     */
    public DirectionsCacheEntry createDirectionsCacheEntry() {
        return new DirectionsCacheEntry();
    }

    /**
     * Create an instance of {@link From }
     * 
     */
    public From createFrom() {
        return new From();
    }

    /**
     * Create an instance of {@link ALatLng }
     * 
     */
    public ALatLng createALatLng() {
        return new ALatLng();
    }

    /**
     * Create an instance of {@link To }
     * 
     */
    public To createTo() {
        return new To();
    }

    /**
     * Create an instance of {@link Sensor }
     * 
     */
    public Sensor createSensor() {
        return new Sensor();
    }

    /**
     * Create an instance of {@link Position }
     * 
     */
    public Position createPosition() {
        return new Position();
    }

    /**
     * Create an instance of {@link LinkReference }
     * 
     */
    public LinkReference createLinkReference() {
        return new LinkReference();
    }

    /**
     * Create an instance of {@link Parameters }
     * 
     */
    public Parameters createParameters() {
        return new Parameters();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link DataSources }
     * 
     */
    public DataSources createDataSources() {
        return new DataSources();
    }

    /**
     * Create an instance of {@link Od }
     * 
     */
    public Od createOd() {
        return new Od();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link TargetElements }
     * 
     */
    public TargetElements createTargetElements() {
        return new TargetElements();
    }

    /**
     * Create an instance of {@link ScenarioElement }
     * 
     */
    public ScenarioElement createScenarioElement() {
        return new ScenarioElement();
    }

    /**
     * Create an instance of {@link OnOffSwitch }
     * 
     */
    public OnOffSwitch createOnOffSwitch() {
        return new OnOffSwitch();
    }

    /**
     * Create an instance of {@link Knob }
     * 
     */
    public Knob createKnob() {
        return new Knob();
    }

    /**
     * Create an instance of {@link SplitratioEvent }
     * 
     */
    public SplitratioEvent createSplitratioEvent() {
        return new SplitratioEvent();
    }

    /**
     * Create an instance of {@link Weavingfactors }
     * 
     */
    public Weavingfactors createWeavingfactors() {
        return new Weavingfactors();
    }

    /**
     * Create an instance of {@link FeedbackElements }
     * 
     */
    public FeedbackElements createFeedbackElements() {
        return new FeedbackElements();
    }

    /**
     * Create an instance of {@link DirectionsCache }
     * 
     */
    public DirectionsCache createDirectionsCache() {
        return new DirectionsCache();
    }

    /**
     * Create an instance of {@link FundamentalDiagramProfile }
     * 
     */
    public FundamentalDiagramProfile createFundamentalDiagramProfile() {
        return new FundamentalDiagramProfile();
    }

    /**
     * Create an instance of {@link SignalList }
     * 
     */
    public SignalList createSignalList() {
        return new SignalList();
    }

    /**
     * Create an instance of {@link Signal }
     * 
     */
    public Signal createSignal() {
        return new Signal();
    }

    /**
     * Create an instance of {@link Phase }
     * 
     */
    public Phase createPhase() {
        return new Phase();
    }

    /**
     * Create an instance of {@link Links }
     * 
     */
    public Links createLinks() {
        return new Links();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link PlanReference }
     * 
     */
    public PlanReference createPlanReference() {
        return new PlanReference();
    }

    /**
     * Create an instance of {@link PathSegment }
     * 
     */
    public PathSegment createPathSegment() {
        return new PathSegment();
    }

    /**
     * Create an instance of {@link FundamentalDiagramProfileSet }
     * 
     */
    public FundamentalDiagramProfileSet createFundamentalDiagramProfileSet() {
        return new FundamentalDiagramProfileSet();
    }

    /**
     * Create an instance of {@link PlanSequence }
     * 
     */
    public PlanSequence createPlanSequence() {
        return new PlanSequence();
    }

    /**
     * Create an instance of {@link Node }
     * 
     */
    public Node createNode() {
        return new Node();
    }

    /**
     * Create an instance of {@link Outputs }
     * 
     */
    public Outputs createOutputs() {
        return new Outputs();
    }

    /**
     * Create an instance of {@link Output }
     * 
     */
    public Output createOutput() {
        return new Output();
    }

    /**
     * Create an instance of {@link Inputs }
     * 
     */
    public Inputs createInputs() {
        return new Inputs();
    }

    /**
     * Create an instance of {@link Input }
     * 
     */
    public Input createInput() {
        return new Input();
    }

    /**
     * Create an instance of {@link ControllerSet }
     * 
     */
    public ControllerSet createControllerSet() {
        return new ControllerSet();
    }

    /**
     * Create an instance of {@link Controller }
     * 
     */
    public Controller createController() {
        return new Controller();
    }

    /**
     * Create an instance of {@link Qcontroller }
     * 
     */
    public Qcontroller createQcontroller() {
        return new Qcontroller();
    }

    /**
     * Create an instance of {@link PlanList }
     * 
     */
    public PlanList createPlanList() {
        return new PlanList();
    }

    /**
     * Create an instance of {@link Plan }
     * 
     */
    public Plan createPlan() {
        return new Plan();
    }

    /**
     * Create an instance of {@link Intersection }
     * 
     */
    public Intersection createIntersection() {
        return new Intersection();
    }

    /**
     * Create an instance of {@link Stage }
     * 
     */
    public Stage createStage() {
        return new Stage();
    }

    /**
     * Create an instance of {@link Scenario }
     * 
     */
    public Scenario createScenario() {
        return new Scenario();
    }

    /**
     * Create an instance of {@link NetworkList }
     * 
     */
    public NetworkList createNetworkList() {
        return new NetworkList();
    }

    /**
     * Create an instance of {@link Network }
     * 
     */
    public Network createNetwork() {
        return new Network();
    }

    /**
     * Create an instance of {@link NodeList }
     * 
     */
    public NodeList createNodeList() {
        return new NodeList();
    }

    /**
     * Create an instance of {@link LinkList }
     * 
     */
    public LinkList createLinkList() {
        return new LinkList();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link Begin }
     * 
     */
    public Begin createBegin() {
        return new Begin();
    }

    /**
     * Create an instance of {@link End }
     * 
     */
    public End createEnd() {
        return new End();
    }

    /**
     * Create an instance of {@link Dynamics }
     * 
     */
    public Dynamics createDynamics() {
        return new Dynamics();
    }

    /**
     * Create an instance of {@link LinkGeometry }
     * 
     */
    public LinkGeometry createLinkGeometry() {
        return new LinkGeometry();
    }

    /**
     * Create an instance of {@link SensorList }
     * 
     */
    public SensorList createSensorList() {
        return new SensorList();
    }

    /**
     * Create an instance of {@link IntersectionCache }
     * 
     */
    public IntersectionCache createIntersectionCache() {
        return new IntersectionCache();
    }

    /**
     * Create an instance of {@link IntersectionCacheEntry }
     * 
     */
    public IntersectionCacheEntry createIntersectionCacheEntry() {
        return new IntersectionCacheEntry();
    }

    /**
     * Create an instance of {@link WeavingFactorsProfile }
     * 
     */
    public WeavingFactorsProfile createWeavingFactorsProfile() {
        return new WeavingFactorsProfile();
    }

    /**
     * Create an instance of {@link SplitRatioProfileSet }
     * 
     */
    public SplitRatioProfileSet createSplitRatioProfileSet() {
        return new SplitRatioProfileSet();
    }

    /**
     * Create an instance of {@link DownstreamBoundaryCapacitySet }
     * 
     */
    public DownstreamBoundaryCapacitySet createDownstreamBoundaryCapacitySet() {
        return new DownstreamBoundaryCapacitySet();
    }

    /**
     * Create an instance of {@link CapacityProfile }
     * 
     */
    public CapacityProfile createCapacityProfile() {
        return new CapacityProfile();
    }

    /**
     * Create an instance of {@link EventSet }
     * 
     */
    public EventSet createEventSet() {
        return new EventSet();
    }

    /**
     * Create an instance of {@link DemandProfileSet }
     * 
     */
    public DemandProfileSet createDemandProfileSet() {
        return new DemandProfileSet();
    }

    /**
     * Create an instance of {@link DemandProfile }
     * 
     */
    public DemandProfile createDemandProfile() {
        return new DemandProfile();
    }

    /**
     * Create an instance of {@link NetworkConnections }
     * 
     */
    public NetworkConnections createNetworkConnections() {
        return new NetworkConnections();
    }

    /**
     * Create an instance of {@link Nertworkpair }
     * 
     */
    public Nertworkpair createNertworkpair() {
        return new Nertworkpair();
    }

    /**
     * Create an instance of {@link Linkpair }
     * 
     */
    public Linkpair createLinkpair() {
        return new Linkpair();
    }

    /**
     * Create an instance of {@link ODList }
     * 
     */
    public ODList createODList() {
        return new ODList();
    }

    /**
     * Create an instance of {@link PathSegements }
     * 
     */
    public PathSegements createPathSegements() {
        return new PathSegements();
    }

    /**
     * Create an instance of {@link ODDemandPofileSet }
     * 
     */
    public ODDemandPofileSet createODDemandPofileSet() {
        return new ODDemandPofileSet();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Levels")
    public JAXBElement<String> createLevels(String value) {
        return new JAXBElement<String>(_Levels_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "path_segments")
    public JAXBElement<String> createPathSegments(String value) {
        return new JAXBElement<String>(_PathSegments_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "postmile")
    public JAXBElement<BigDecimal> createPostmile(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Postmile_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "decision_points")
    public JAXBElement<String> createDecisionPoints(String value) {
        return new JAXBElement<String>(_DecisionPoints_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Points")
    public JAXBElement<String> createPoints(String value) {
        return new JAXBElement<String>(_Points_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "units")
    public JAXBElement<String> createUnits(String value) {
        return new JAXBElement<String>(_Units_QNAME, String.class, null, value);
    }

}
