//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.28 at 12:55:28 PM PST 
//


package com.relteq.sirius.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}path_segments" minOccurs="0"/>
 *         &lt;element ref="{}decision_points" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="network_id_origin" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="link_id_origin" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="network_id_destination" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="link_id_destination" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pathSegments",
    "decisionPoints"
})
@XmlRootElement(name = "od")
public class Od {

    @XmlElement(name = "path_segments")
    protected String pathSegments;
    @XmlElement(name = "decision_points")
    protected String decisionPoints;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "network_id_origin")
    protected String networkIdOrigin;
    @XmlAttribute(name = "link_id_origin", required = true)
    protected String linkIdOrigin;
    @XmlAttribute(name = "network_id_destination")
    protected String networkIdDestination;
    @XmlAttribute(name = "link_id_destination", required = true)
    protected String linkIdDestination;

    /**
     * Gets the value of the pathSegments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPathSegments() {
        return pathSegments;
    }

    /**
     * Sets the value of the pathSegments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPathSegments(String value) {
        this.pathSegments = value;
    }

    /**
     * Gets the value of the decisionPoints property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecisionPoints() {
        return decisionPoints;
    }

    /**
     * Sets the value of the decisionPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecisionPoints(String value) {
        this.decisionPoints = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the networkIdOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkIdOrigin() {
        return networkIdOrigin;
    }

    /**
     * Sets the value of the networkIdOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkIdOrigin(String value) {
        this.networkIdOrigin = value;
    }

    /**
     * Gets the value of the linkIdOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkIdOrigin() {
        return linkIdOrigin;
    }

    /**
     * Sets the value of the linkIdOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkIdOrigin(String value) {
        this.linkIdOrigin = value;
    }

    /**
     * Gets the value of the networkIdDestination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkIdDestination() {
        return networkIdDestination;
    }

    /**
     * Sets the value of the networkIdDestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkIdDestination(String value) {
        this.networkIdDestination = value;
    }

    /**
     * Gets the value of the linkIdDestination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkIdDestination() {
        return linkIdDestination;
    }

    /**
     * Sets the value of the linkIdDestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkIdDestination(String value) {
        this.linkIdDestination = value;
    }

}
