//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.29 at 04:19:00 PM PST 
//


package com.relteq.sirius.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}description" minOccurs="0"/>
 *         &lt;element ref="{}settings"/>
 *         &lt;element ref="{}NetworkList" minOccurs="0"/>
 *         &lt;element ref="{}InitialDensityProfile" minOccurs="0"/>
 *         &lt;element ref="{}WeavingFactorsProfile" minOccurs="0"/>
 *         &lt;element ref="{}SplitRatioProfileSet" minOccurs="0"/>
 *         &lt;element ref="{}DownstreamBoundaryCapacitySet" minOccurs="0"/>
 *         &lt;element ref="{}EventSet" minOccurs="0"/>
 *         &lt;element ref="{}DemandProfileSet" minOccurs="0"/>
 *         &lt;element ref="{}ControllerSet" minOccurs="0"/>
 *         &lt;element ref="{}FundamentalDiagramProfileSet" minOccurs="0"/>
 *         &lt;element ref="{}NetworkConnections" minOccurs="0"/>
 *         &lt;element ref="{}ODList" minOccurs="0"/>
 *         &lt;element ref="{}PathSegements" minOccurs="0"/>
 *         &lt;element ref="{}DecisionPoints" minOccurs="0"/>
 *         &lt;element ref="{}ODDemandPofileSet" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="schemaVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "scenario")
public class Scenario {

    protected String description;
    @XmlElement(required = true)
    protected Settings settings;
    @XmlElement(name = "NetworkList")
    protected NetworkList networkList;
    @XmlElement(name = "InitialDensityProfile")
    protected InitialDensityProfile initialDensityProfile;
    @XmlElement(name = "WeavingFactorsProfile")
    protected WeavingFactorsProfile weavingFactorsProfile;
    @XmlElement(name = "SplitRatioProfileSet")
    protected SplitRatioProfileSet splitRatioProfileSet;
    @XmlElement(name = "DownstreamBoundaryCapacitySet")
    protected DownstreamBoundaryCapacitySet downstreamBoundaryCapacitySet;
    @XmlElement(name = "EventSet")
    protected EventSet eventSet;
    @XmlElement(name = "DemandProfileSet")
    protected DemandProfileSet demandProfileSet;
    @XmlElement(name = "ControllerSet")
    protected ControllerSet controllerSet;
    @XmlElement(name = "FundamentalDiagramProfileSet")
    protected FundamentalDiagramProfileSet fundamentalDiagramProfileSet;
    @XmlElement(name = "NetworkConnections")
    protected NetworkConnections networkConnections;
    @XmlElement(name = "ODList")
    protected ODList odList;
    @XmlElement(name = "PathSegements")
    protected PathSegements pathSegements;
    @XmlElement(name = "DecisionPoints")
    protected DecisionPoints decisionPoints;
    @XmlElement(name = "ODDemandPofileSet")
    protected ODDemandPofileSet odDemandPofileSet;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "schemaVersion", required = true)
    protected String schemaVersion;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the settings property.
     * 
     * @return
     *     possible object is
     *     {@link Settings }
     *     
     */
    public Settings getSettings() {
        return settings;
    }

    /**
     * Sets the value of the settings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Settings }
     *     
     */
    public void setSettings(Settings value) {
        this.settings = value;
    }

    /**
     * Gets the value of the networkList property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkList }
     *     
     */
    public NetworkList getNetworkList() {
        return networkList;
    }

    /**
     * Sets the value of the networkList property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkList }
     *     
     */
    public void setNetworkList(NetworkList value) {
        this.networkList = value;
    }

    /**
     * Gets the value of the initialDensityProfile property.
     * 
     * @return
     *     possible object is
     *     {@link InitialDensityProfile }
     *     
     */
    public InitialDensityProfile getInitialDensityProfile() {
        return initialDensityProfile;
    }

    /**
     * Sets the value of the initialDensityProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitialDensityProfile }
     *     
     */
    public void setInitialDensityProfile(InitialDensityProfile value) {
        this.initialDensityProfile = value;
    }

    /**
     * Gets the value of the weavingFactorsProfile property.
     * 
     * @return
     *     possible object is
     *     {@link WeavingFactorsProfile }
     *     
     */
    public WeavingFactorsProfile getWeavingFactorsProfile() {
        return weavingFactorsProfile;
    }

    /**
     * Sets the value of the weavingFactorsProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link WeavingFactorsProfile }
     *     
     */
    public void setWeavingFactorsProfile(WeavingFactorsProfile value) {
        this.weavingFactorsProfile = value;
    }

    /**
     * Gets the value of the splitRatioProfileSet property.
     * 
     * @return
     *     possible object is
     *     {@link SplitRatioProfileSet }
     *     
     */
    public SplitRatioProfileSet getSplitRatioProfileSet() {
        return splitRatioProfileSet;
    }

    /**
     * Sets the value of the splitRatioProfileSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link SplitRatioProfileSet }
     *     
     */
    public void setSplitRatioProfileSet(SplitRatioProfileSet value) {
        this.splitRatioProfileSet = value;
    }

    /**
     * Gets the value of the downstreamBoundaryCapacitySet property.
     * 
     * @return
     *     possible object is
     *     {@link DownstreamBoundaryCapacitySet }
     *     
     */
    public DownstreamBoundaryCapacitySet getDownstreamBoundaryCapacitySet() {
        return downstreamBoundaryCapacitySet;
    }

    /**
     * Sets the value of the downstreamBoundaryCapacitySet property.
     * 
     * @param value
     *     allowed object is
     *     {@link DownstreamBoundaryCapacitySet }
     *     
     */
    public void setDownstreamBoundaryCapacitySet(DownstreamBoundaryCapacitySet value) {
        this.downstreamBoundaryCapacitySet = value;
    }

    /**
     * Gets the value of the eventSet property.
     * 
     * @return
     *     possible object is
     *     {@link EventSet }
     *     
     */
    public EventSet getEventSet() {
        return eventSet;
    }

    /**
     * Sets the value of the eventSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventSet }
     *     
     */
    public void setEventSet(EventSet value) {
        this.eventSet = value;
    }

    /**
     * Gets the value of the demandProfileSet property.
     * 
     * @return
     *     possible object is
     *     {@link DemandProfileSet }
     *     
     */
    public DemandProfileSet getDemandProfileSet() {
        return demandProfileSet;
    }

    /**
     * Sets the value of the demandProfileSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link DemandProfileSet }
     *     
     */
    public void setDemandProfileSet(DemandProfileSet value) {
        this.demandProfileSet = value;
    }

    /**
     * Gets the value of the controllerSet property.
     * 
     * @return
     *     possible object is
     *     {@link ControllerSet }
     *     
     */
    public ControllerSet getControllerSet() {
        return controllerSet;
    }

    /**
     * Sets the value of the controllerSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControllerSet }
     *     
     */
    public void setControllerSet(ControllerSet value) {
        this.controllerSet = value;
    }

    /**
     * Gets the value of the fundamentalDiagramProfileSet property.
     * 
     * @return
     *     possible object is
     *     {@link FundamentalDiagramProfileSet }
     *     
     */
    public FundamentalDiagramProfileSet getFundamentalDiagramProfileSet() {
        return fundamentalDiagramProfileSet;
    }

    /**
     * Sets the value of the fundamentalDiagramProfileSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link FundamentalDiagramProfileSet }
     *     
     */
    public void setFundamentalDiagramProfileSet(FundamentalDiagramProfileSet value) {
        this.fundamentalDiagramProfileSet = value;
    }

    /**
     * Gets the value of the networkConnections property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkConnections }
     *     
     */
    public NetworkConnections getNetworkConnections() {
        return networkConnections;
    }

    /**
     * Sets the value of the networkConnections property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkConnections }
     *     
     */
    public void setNetworkConnections(NetworkConnections value) {
        this.networkConnections = value;
    }

    /**
     * Gets the value of the odList property.
     * 
     * @return
     *     possible object is
     *     {@link ODList }
     *     
     */
    public ODList getODList() {
        return odList;
    }

    /**
     * Sets the value of the odList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ODList }
     *     
     */
    public void setODList(ODList value) {
        this.odList = value;
    }

    /**
     * Gets the value of the pathSegements property.
     * 
     * @return
     *     possible object is
     *     {@link PathSegements }
     *     
     */
    public PathSegements getPathSegements() {
        return pathSegements;
    }

    /**
     * Sets the value of the pathSegements property.
     * 
     * @param value
     *     allowed object is
     *     {@link PathSegements }
     *     
     */
    public void setPathSegements(PathSegements value) {
        this.pathSegements = value;
    }

    /**
     * Gets the value of the decisionPoints property.
     * 
     * @return
     *     possible object is
     *     {@link DecisionPoints }
     *     
     */
    public DecisionPoints getDecisionPoints() {
        return decisionPoints;
    }

    /**
     * Sets the value of the decisionPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link DecisionPoints }
     *     
     */
    public void setDecisionPoints(DecisionPoints value) {
        this.decisionPoints = value;
    }

    /**
     * Gets the value of the odDemandPofileSet property.
     * 
     * @return
     *     possible object is
     *     {@link ODDemandPofileSet }
     *     
     */
    public ODDemandPofileSet getODDemandPofileSet() {
        return odDemandPofileSet;
    }

    /**
     * Sets the value of the odDemandPofileSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link ODDemandPofileSet }
     *     
     */
    public void setODDemandPofileSet(ODDemandPofileSet value) {
        this.odDemandPofileSet = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the schemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaVersion() {
        return schemaVersion;
    }

    /**
     * Sets the value of the schemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaVersion(String value) {
        this.schemaVersion = value;
    }

}
