//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.14 at 11:41:53 AM PST 
//


package com.relteq.sirius.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}VehicleTypes" minOccurs="0"/>
 *         &lt;element ref="{}units"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "settings")
public class Settings {

    @XmlElement(name = "VehicleTypes")
    protected VehicleTypes vehicleTypes;
    @XmlElement(required = true)
    protected String units;

    /**
     * Gets the value of the vehicleTypes property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleTypes }
     *     
     */
    public VehicleTypes getVehicleTypes() {
        return vehicleTypes;
    }

    /**
     * Sets the value of the vehicleTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleTypes }
     *     
     */
    public void setVehicleTypes(VehicleTypes value) {
        this.vehicleTypes = value;
    }

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnits(String value) {
        this.units = value;
    }

}
