//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.27 at 09:10:04 AM PST 
//


package com.relteq.sirius.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="timeMax" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="outputDt" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="timeInitial" type="{http://www.w3.org/2001/XMLSchema}decimal" default="0.0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "simulation")
public class Simulation {

    @XmlAttribute(name = "timeMax", required = true)
    protected BigDecimal timeMax;
    @XmlAttribute(name = "outputDt", required = true)
    protected BigDecimal outputDt;
    @XmlAttribute(name = "timeInitial")
    protected BigDecimal timeInitial;

    /**
     * Gets the value of the timeMax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTimeMax() {
        return timeMax;
    }

    /**
     * Sets the value of the timeMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTimeMax(BigDecimal value) {
        this.timeMax = value;
    }

    /**
     * Gets the value of the outputDt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOutputDt() {
        return outputDt;
    }

    /**
     * Sets the value of the outputDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOutputDt(BigDecimal value) {
        this.outputDt = value;
    }

    /**
     * Gets the value of the timeInitial property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTimeInitial() {
        if (timeInitial == null) {
            return new BigDecimal("0.0");
        } else {
            return timeInitial;
        }
    }

    /**
     * Sets the value of the timeInitial property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTimeInitial(BigDecimal value) {
        this.timeInitial = value;
    }

}
