//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.23 at 08:38:57 AM PST 
//


package aurora.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}components" minOccurs="0"/>
 *         &lt;element ref="{}zones" minOccurs="0"/>
 *         &lt;element ref="{}onramps" minOccurs="0"/>
 *         &lt;element ref="{}parameters" minOccurs="0"/>
 *         &lt;element ref="{}limits" minOccurs="0"/>
 *         &lt;element ref="{}qcontroller" minOccurs="0"/>
 *         &lt;element ref="{}table" minOccurs="0"/>
 *         &lt;element ref="{}display_position" minOccurs="0"/>
 *         &lt;element ref="{}PlanSequence" minOccurs="0"/>
 *         &lt;element ref="{}PlanList" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="ALINEA|TOD|TR|VSLTOD|SIMPLESIGNAL|PRETIMED|ACTUADED|SYNCHRONIZED|SWARM|HERO|SLAVE"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="dt" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="usesensors" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="node_id" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="link_id" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *       &lt;attribute name="network_id" type="{http://www.w3.org/2001/XMLSchema}string" default="" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "controller")
public class Controller {

    protected Components components;
    protected Zones zones;
    protected Onramps onramps;
    protected Parameters parameters;
    protected Limits limits;
    protected Qcontroller qcontroller;
    protected Table table;
    @XmlElement(name = "display_position")
    protected DisplayPosition displayPosition;
    @XmlElement(name = "PlanSequence")
    protected PlanSequence planSequence;
    @XmlElement(name = "PlanList")
    protected PlanList planList;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "dt", required = true)
    protected BigDecimal dt;
    @XmlAttribute(name = "usesensors")
    protected Boolean usesensors;
    @XmlAttribute(name = "node_id")
    protected String nodeId;
    @XmlAttribute(name = "link_id")
    protected String linkId;
    @XmlAttribute(name = "network_id")
    protected String networkId;

    /**
     * Gets the value of the components property.
     * 
     * @return
     *     possible object is
     *     {@link Components }
     *     
     */
    public Components getComponents() {
        return components;
    }

    /**
     * Sets the value of the components property.
     * 
     * @param value
     *     allowed object is
     *     {@link Components }
     *     
     */
    public void setComponents(Components value) {
        this.components = value;
    }

    /**
     * Gets the value of the zones property.
     * 
     * @return
     *     possible object is
     *     {@link Zones }
     *     
     */
    public Zones getZones() {
        return zones;
    }

    /**
     * Sets the value of the zones property.
     * 
     * @param value
     *     allowed object is
     *     {@link Zones }
     *     
     */
    public void setZones(Zones value) {
        this.zones = value;
    }

    /**
     * Gets the value of the onramps property.
     * 
     * @return
     *     possible object is
     *     {@link Onramps }
     *     
     */
    public Onramps getOnramps() {
        return onramps;
    }

    /**
     * Sets the value of the onramps property.
     * 
     * @param value
     *     allowed object is
     *     {@link Onramps }
     *     
     */
    public void setOnramps(Onramps value) {
        this.onramps = value;
    }

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link Parameters }
     *     
     */
    public Parameters getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parameters }
     *     
     */
    public void setParameters(Parameters value) {
        this.parameters = value;
    }

    /**
     * Gets the value of the limits property.
     * 
     * @return
     *     possible object is
     *     {@link Limits }
     *     
     */
    public Limits getLimits() {
        return limits;
    }

    /**
     * Sets the value of the limits property.
     * 
     * @param value
     *     allowed object is
     *     {@link Limits }
     *     
     */
    public void setLimits(Limits value) {
        this.limits = value;
    }

    /**
     * Gets the value of the qcontroller property.
     * 
     * @return
     *     possible object is
     *     {@link Qcontroller }
     *     
     */
    public Qcontroller getQcontroller() {
        return qcontroller;
    }

    /**
     * Sets the value of the qcontroller property.
     * 
     * @param value
     *     allowed object is
     *     {@link Qcontroller }
     *     
     */
    public void setQcontroller(Qcontroller value) {
        this.qcontroller = value;
    }

    /**
     * Gets the value of the table property.
     * 
     * @return
     *     possible object is
     *     {@link Table }
     *     
     */
    public Table getTable() {
        return table;
    }

    /**
     * Sets the value of the table property.
     * 
     * @param value
     *     allowed object is
     *     {@link Table }
     *     
     */
    public void setTable(Table value) {
        this.table = value;
    }

    /**
     * Gets the value of the displayPosition property.
     * 
     * @return
     *     possible object is
     *     {@link DisplayPosition }
     *     
     */
    public DisplayPosition getDisplayPosition() {
        return displayPosition;
    }

    /**
     * Sets the value of the displayPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisplayPosition }
     *     
     */
    public void setDisplayPosition(DisplayPosition value) {
        this.displayPosition = value;
    }

    /**
     * Gets the value of the planSequence property.
     * 
     * @return
     *     possible object is
     *     {@link PlanSequence }
     *     
     */
    public PlanSequence getPlanSequence() {
        return planSequence;
    }

    /**
     * Sets the value of the planSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanSequence }
     *     
     */
    public void setPlanSequence(PlanSequence value) {
        this.planSequence = value;
    }

    /**
     * Gets the value of the planList property.
     * 
     * @return
     *     possible object is
     *     {@link PlanList }
     *     
     */
    public PlanList getPlanList() {
        return planList;
    }

    /**
     * Sets the value of the planList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlanList }
     *     
     */
    public void setPlanList(PlanList value) {
        this.planList = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the dt property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDt() {
        return dt;
    }

    /**
     * Sets the value of the dt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDt(BigDecimal value) {
        this.dt = value;
    }

    /**
     * Gets the value of the usesensors property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isUsesensors() {
        if (usesensors == null) {
            return false;
        } else {
            return usesensors;
        }
    }

    /**
     * Sets the value of the usesensors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUsesensors(Boolean value) {
        this.usesensors = value;
    }

    /**
     * Gets the value of the nodeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodeId() {
        if (nodeId == null) {
            return "";
        } else {
            return nodeId;
        }
    }

    /**
     * Sets the value of the nodeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodeId(String value) {
        this.nodeId = value;
    }

    /**
     * Gets the value of the linkId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkId() {
        if (linkId == null) {
            return "";
        } else {
            return linkId;
        }
    }

    /**
     * Sets the value of the linkId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkId(String value) {
        this.linkId = value;
    }

    /**
     * Gets the value of the networkId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkId() {
        if (networkId == null) {
            return "";
        } else {
            return networkId;
        }
    }

    /**
     * Sets the value of the networkId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkId(String value) {
        this.networkId = value;
    }

}
