//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.23 at 08:38:57 AM PST 
//


package aurora.jaxb;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}links" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="nema" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="protected" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="permissive" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="yellow_time" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="red_clear_time" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="min_green_time" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="lag" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="recall" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "phase")
public class Phase {

    protected Links links;
    @XmlAttribute(name = "nema", required = true)
    protected BigInteger nema;
    @XmlAttribute(name = "protected", required = true)
    protected boolean _protected;
    @XmlAttribute(name = "permissive", required = true)
    protected boolean permissive;
    @XmlAttribute(name = "yellow_time", required = true)
    protected BigDecimal yellowTime;
    @XmlAttribute(name = "red_clear_time", required = true)
    protected BigDecimal redClearTime;
    @XmlAttribute(name = "min_green_time", required = true)
    protected BigDecimal minGreenTime;
    @XmlAttribute(name = "lag", required = true)
    protected boolean lag;
    @XmlAttribute(name = "recall", required = true)
    protected boolean recall;

    /**
     * Gets the value of the links property.
     * 
     * @return
     *     possible object is
     *     {@link Links }
     *     
     */
    public Links getLinks() {
        return links;
    }

    /**
     * Sets the value of the links property.
     * 
     * @param value
     *     allowed object is
     *     {@link Links }
     *     
     */
    public void setLinks(Links value) {
        this.links = value;
    }

    /**
     * Gets the value of the nema property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNema() {
        return nema;
    }

    /**
     * Sets the value of the nema property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNema(BigInteger value) {
        this.nema = value;
    }

    /**
     * Gets the value of the protected property.
     * 
     */
    public boolean isProtected() {
        return _protected;
    }

    /**
     * Sets the value of the protected property.
     * 
     */
    public void setProtected(boolean value) {
        this._protected = value;
    }

    /**
     * Gets the value of the permissive property.
     * 
     */
    public boolean isPermissive() {
        return permissive;
    }

    /**
     * Sets the value of the permissive property.
     * 
     */
    public void setPermissive(boolean value) {
        this.permissive = value;
    }

    /**
     * Gets the value of the yellowTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getYellowTime() {
        return yellowTime;
    }

    /**
     * Sets the value of the yellowTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setYellowTime(BigDecimal value) {
        this.yellowTime = value;
    }

    /**
     * Gets the value of the redClearTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRedClearTime() {
        return redClearTime;
    }

    /**
     * Sets the value of the redClearTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRedClearTime(BigDecimal value) {
        this.redClearTime = value;
    }

    /**
     * Gets the value of the minGreenTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMinGreenTime() {
        return minGreenTime;
    }

    /**
     * Sets the value of the minGreenTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMinGreenTime(BigDecimal value) {
        this.minGreenTime = value;
    }

    /**
     * Gets the value of the lag property.
     * 
     */
    public boolean isLag() {
        return lag;
    }

    /**
     * Sets the value of the lag property.
     * 
     */
    public void setLag(boolean value) {
        this.lag = value;
    }

    /**
     * Gets the value of the recall property.
     * 
     */
    public boolean isRecall() {
        return recall;
    }

    /**
     * Sets the value of the recall property.
     * 
     */
    public void setRecall(boolean value) {
        this.recall = value;
    }

}
