//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.03 at 03:10:39 PM PDT 
//


package jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="mainline" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="queue" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "control")
public class Control {

    @XmlAttribute(name = "mainline", required = true)
    protected boolean mainline;
    @XmlAttribute(name = "queue", required = true)
    protected boolean queue;

    /**
     * Gets the value of the mainline property.
     * 
     */
    public boolean isMainline() {
        return mainline;
    }

    /**
     * Sets the value of the mainline property.
     * 
     */
    public void setMainline(boolean value) {
        this.mainline = value;
    }

    /**
     * Gets the value of the queue property.
     * 
     */
    public boolean isQueue() {
        return queue;
    }

    /**
     * Sets the value of the queue property.
     * 
     */
    public void setQueue(boolean value) {
        this.queue = value;
    }

}
