//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.03 at 03:10:39 PM PDT 
//


package jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}description" minOccurs="0"/>
 *         &lt;element ref="{}network"/>
 *         &lt;element ref="{}settings"/>
 *         &lt;element ref="{}InitialDensityProfile" minOccurs="0"/>
 *         &lt;element ref="{}SplitRatioProfileSet" minOccurs="0"/>
 *         &lt;element ref="{}CapacityProfileSet" minOccurs="0"/>
 *         &lt;element ref="{}EventSet" minOccurs="0"/>
 *         &lt;element ref="{}DemandProfileSet" minOccurs="0"/>
 *         &lt;element ref="{}ControllerSet" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="schemaVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "scenario")
public class Scenario {

    protected String description;
    @XmlElement(required = true)
    protected Network network;
    @XmlElement(required = true)
    protected Settings settings;
    @XmlElement(name = "InitialDensityProfile")
    protected InitialDensityProfile initialDensityProfile;
    @XmlElement(name = "SplitRatioProfileSet")
    protected SplitRatioProfileSet splitRatioProfileSet;
    @XmlElement(name = "CapacityProfileSet")
    protected CapacityProfileSet capacityProfileSet;
    @XmlElement(name = "EventSet")
    protected EventSet eventSet;
    @XmlElement(name = "DemandProfileSet")
    protected DemandProfileSet demandProfileSet;
    @XmlElement(name = "ControllerSet")
    protected ControllerSet controllerSet;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "schemaVersion", required = true)
    protected String schemaVersion;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the network property.
     * 
     * @return
     *     possible object is
     *     {@link Network }
     *     
     */
    public Network getNetwork() {
        return network;
    }

    /**
     * Sets the value of the network property.
     * 
     * @param value
     *     allowed object is
     *     {@link Network }
     *     
     */
    public void setNetwork(Network value) {
        this.network = value;
    }

    /**
     * Gets the value of the settings property.
     * 
     * @return
     *     possible object is
     *     {@link Settings }
     *     
     */
    public Settings getSettings() {
        return settings;
    }

    /**
     * Sets the value of the settings property.
     * 
     * @param value
     *     allowed object is
     *     {@link Settings }
     *     
     */
    public void setSettings(Settings value) {
        this.settings = value;
    }

    /**
     * Gets the value of the initialDensityProfile property.
     * 
     * @return
     *     possible object is
     *     {@link InitialDensityProfile }
     *     
     */
    public InitialDensityProfile getInitialDensityProfile() {
        return initialDensityProfile;
    }

    /**
     * Sets the value of the initialDensityProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitialDensityProfile }
     *     
     */
    public void setInitialDensityProfile(InitialDensityProfile value) {
        this.initialDensityProfile = value;
    }

    /**
     * Gets the value of the splitRatioProfileSet property.
     * 
     * @return
     *     possible object is
     *     {@link SplitRatioProfileSet }
     *     
     */
    public SplitRatioProfileSet getSplitRatioProfileSet() {
        return splitRatioProfileSet;
    }

    /**
     * Sets the value of the splitRatioProfileSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link SplitRatioProfileSet }
     *     
     */
    public void setSplitRatioProfileSet(SplitRatioProfileSet value) {
        this.splitRatioProfileSet = value;
    }

    /**
     * Gets the value of the capacityProfileSet property.
     * 
     * @return
     *     possible object is
     *     {@link CapacityProfileSet }
     *     
     */
    public CapacityProfileSet getCapacityProfileSet() {
        return capacityProfileSet;
    }

    /**
     * Sets the value of the capacityProfileSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapacityProfileSet }
     *     
     */
    public void setCapacityProfileSet(CapacityProfileSet value) {
        this.capacityProfileSet = value;
    }

    /**
     * Gets the value of the eventSet property.
     * 
     * @return
     *     possible object is
     *     {@link EventSet }
     *     
     */
    public EventSet getEventSet() {
        return eventSet;
    }

    /**
     * Sets the value of the eventSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventSet }
     *     
     */
    public void setEventSet(EventSet value) {
        this.eventSet = value;
    }

    /**
     * Gets the value of the demandProfileSet property.
     * 
     * @return
     *     possible object is
     *     {@link DemandProfileSet }
     *     
     */
    public DemandProfileSet getDemandProfileSet() {
        return demandProfileSet;
    }

    /**
     * Sets the value of the demandProfileSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link DemandProfileSet }
     *     
     */
    public void setDemandProfileSet(DemandProfileSet value) {
        this.demandProfileSet = value;
    }

    /**
     * Gets the value of the controllerSet property.
     * 
     * @return
     *     possible object is
     *     {@link ControllerSet }
     *     
     */
    public ControllerSet getControllerSet() {
        return controllerSet;
    }

    /**
     * Sets the value of the controllerSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControllerSet }
     *     
     */
    public void setControllerSet(ControllerSet value) {
        this.controllerSet = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the schemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaVersion() {
        return schemaVersion;
    }

    /**
     * Sets the value of the schemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaVersion(String value) {
        this.schemaVersion = value;
    }

}
