/*  Copyright (c) 2012, Relteq Systems, Inc. All rights reserved.
	This source is subject to the following copyright notice:
	http://relteq.com/COPYRIGHT_RelteqSystemsInc.txt
*/

package com.relteq.sirius.simulator;

import java.util.ArrayList;

import com.relteq.sirius.jaxb.Controller;
import com.relteq.sirius.jaxb.ScenarioElement;

public abstract class _Controller implements InterfaceController{
	
	protected String name;			// This is used only for controller on/off events.
									// would prefer to reference contorllers by id. 
	protected Types.Controller myType;
	protected ArrayList<_ScenarioElement> targets;
	protected ArrayList<_ScenarioElement> feedbacks;

	protected double dtinseconds;
	protected int samplesteps;
	protected boolean ison;

	/////////////////////////////////////////////////////////////////////
	// construction
	/////////////////////////////////////////////////////////////////////

	// copy jaxb info in constructor instead of initialize
	// because _Controller does not inherit Controller, so the data is not
	// available to this object. _Controller is not a subclass of Controller
	// because what we are really calling are the specific implementations such
	// as ControllerAlinea, and these cannot be generated by createController.
	public _Controller(Controller c,Types.Controller myType){
		this.myType = myType;
		this.name = c.getName();
		this.ison = true;
		dtinseconds = c.getDt().floatValue();		// assume given in seconds
		samplesteps = Utils.round(dtinseconds/Utils.simdtinseconds);

		// store targets ......
		targets = new ArrayList<_ScenarioElement>();
		if(c.getTargetElements()!=null)
			for(ScenarioElement s : c.getTargetElements().getScenarioElement() )
				targets.add( new _ScenarioElement(s) );	

		// store feedbacks ......
		feedbacks = new ArrayList<_ScenarioElement>();
		if(c.getFeedbackElements()!=null)
			for(ScenarioElement s : c.getFeedbackElements().getScenarioElement())
				feedbacks.add( new _ScenarioElement(s) );	
		
		// register controller with targets
		for(_ScenarioElement s : targets){
			boolean registersuccess = false;
			switch(s.myType){
			case link:
				_Link link = Utils.getLinkWithCompositeId(s.network_id,s.id);
				registersuccess = link.registerController();
			case node:
				_Node node = Utils.getNodeWithCompositeId(s.network_id,s.id);
				registersuccess = node.registerController();	
			}
			if(!registersuccess){
				targets = null;		// cause validation failure.
				return;
			}
		}

	}
	
	/////////////////////////////////////////////////////////////////////
	// interface
	/////////////////////////////////////////////////////////////////////
	
	public Types.Controller getMyType() {
		return myType;
	}
	
	/////////////////////////////////////////////////////////////////////
	// actuation
	/////////////////////////////////////////////////////////////////////
	
	protected void setLinkMaxFlow(double desiredvehrate){
		if(!ison)
			return;
		double rate = desiredvehrate;
//		rate = Math.max(rate, minrate);
//		rate = Math.min(rate, maxrate);
		for(_ScenarioElement s: targets){
			((_Link)s.reference).setControl_maxflow( rate );
		}
	}
	
//	protected void setNodeSplitRatio(...){
//	if(!ison)
//	return;
//	}
	
//	protected void set LinkMaxSpeed(){
//	if(!ison)
//	return;	
//	}
	
	/////////////////////////////////////////////////////////////////////
	// initialize / validate / reset / update
	/////////////////////////////////////////////////////////////////////
	
	public boolean validate() {
		
		// check that the target is valid
		if(targets==null){
			System.out.println("Target is invalid or has multiple controllers.");
			return false;
		}
		
		// check that sample dt is an integer multiple of network dt
		if(!Utils.isintegermultipleof(dtinseconds,Utils.simdtinseconds)){
			System.out.println("Controller sample time must be integer multiple of simulation time step.");
			return false;
		}
		
		return true;
	}

	public void reset() {
		ison = true;
	}
	
	public void update() {
	}

}
