/*  Copyright (c) 2012, Relteq Systems, Inc. All rights reserved.
	This source is subject to the following copyright notice:
	http://relteq.com/COPYRIGHT_RelteqSystemsInc.txt
*/

package com.relteq.sirius.simulator;

public abstract class _Sensor implements InterfaceSensor {

	protected static enum Type	{NULL, static_point,
						   	   	       static_area,
						   	   	       moving_point };
	   	   	   		
	protected static enum DataSourceType {NULL, PeMSDataClearinghouse,
										        CaltransDBX,
										        BHL };
						   											   
	protected String id;
	protected _Sensor.Type myType;
	protected _Link myLink = null;

	// copy jaxb info in constructor instead of populate
	// because _Sensor does not inherit Sensor, so the data is not
	// available to this object. _Sensor is not a subclass of Sensor
	// because what we are really calling are the specific implementations such
	// as SensorLoopStation, and these cannot be generated by createSensor.
	public _Sensor(com.relteq.sirius.jaxb.Sensor s,_Sensor.Type myType){
		this.myType = myType;
		this.id = s.getId();
		if(s.getLinkReference()!=null)
			myLink = Utils.getLinkWithCompositeId(s.getLinkReference().getNetworkId(),s.getLinkReference().getId());
	}

	/////////////////////////////////////////////////////////////////////
	// interface
	/////////////////////////////////////////////////////////////////////

	public String getId() {
		return id;
	}

	public _Sensor.Type getMyType() {
		return myType;
	}

	public _Link getMyLink() {
		return myLink;
	}
	
	
}
